// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2tANy9WZ6BVXoDhZrnmZuyazGjRfo79Q',
    appId: '1:718752567715:web:2de49e116d8a42ed3dca16',
    messagingSenderId: '718752567715',
    projectId: 'webrtc-practice-943cb',
    authDomain: 'webrtc-practice-943cb.firebaseapp.com',
    storageBucket: 'webrtc-practice-943cb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjb8Gd1vPsONnCBvz8O5ZHOC_raUh94Xc',
    appId: '1:718752567715:android:99117ba82e8146a33dca16',
    messagingSenderId: '718752567715',
    projectId: 'webrtc-practice-943cb',
    storageBucket: 'webrtc-practice-943cb.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNu5zhe1UKv5ItbOC4LCYYdonPa_7uA24',
    appId: '1:718752567715:ios:655e3fc0eff08d683dca16',
    messagingSenderId: '718752567715',
    projectId: 'webrtc-practice-943cb',
    storageBucket: 'webrtc-practice-943cb.firebasestorage.app',
    iosBundleId: 'com.example.firebaseChatbot',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNu5zhe1UKv5ItbOC4LCYYdonPa_7uA24',
    appId: '1:718752567715:ios:655e3fc0eff08d683dca16',
    messagingSenderId: '718752567715',
    projectId: 'webrtc-practice-943cb',
    storageBucket: 'webrtc-practice-943cb.firebasestorage.app',
    iosBundleId: 'com.example.firebaseChatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2tANy9WZ6BVXoDhZrnmZuyazGjRfo79Q',
    appId: '1:718752567715:web:2de49e116d8a42ed3dca16',
    messagingSenderId: '718752567715',
    projectId: 'webrtc-practice-943cb',
    authDomain: 'webrtc-practice-943cb.firebaseapp.com',
    storageBucket: 'webrtc-practice-943cb.firebasestorage.app',
  );
}
