  # This file contains the fastlane.tools configuration
  # You can find the documentation at https://docs.fastlane.tools
  #
  # For a list of all available actions, check out
  #
  #     https://docs.fastlane.tools/actions
  #
  # For a list of all available plugins, check out
  #
  #     https://docs.fastlane.tools/plugins/available-plugins
  #

  # Uncomment the line if you want fastlane to automatically update itself
  # update_fastlane

  default_platform(:android)

  platform :android do
    desc "Runs all the tests"
    lane :test do
      gradle(task: "test")
    end

    desc "Submit a new Beta Build to Crashlytics Beta"
    lane :firebase do
      build_android_app(
    task: "assemble",
    build_type: "Release"
  )
      gradle(task: "assembleRelease")
      firebase_app_distribution(
        app: "1:588478581327:android:5c9901012a00ece9c9783a",
        testers: "shravani.s@nativewit.in",
        apk_path: "../build/app/outputs/apk/release/app-release.apk"
      )
    end
    
      # sh "your_script.sh"
      # You can also use other beta testing services here


    desc "Deploy a new version to the Google Play"
    lane :deploy do
      gradle(task: "clean assembleRelease")
      upload_to_play_store
    end
  end
