// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-037x_qckmCuO4UFee6L9inf3MyjzYjA',
    appId: '1:588478581327:web:b006fa1945738b54c9783a',
    messagingSenderId: '588478581327',
    projectId: 'namma-kadai-d7220',
    authDomain: 'namma-kadai-d7220.firebaseapp.com',
    storageBucket: 'namma-kadai-d7220.firebasestorage.app',
    measurementId: 'G-JJH6S2YSBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1X7GmIF2vMiowPGCtZYlWbIAoNh-HtSQ',
    appId: '1:588478581327:android:800bd953bc4ec94fc9783a',
    messagingSenderId: '588478581327',
    projectId: 'namma-kadai-d7220',
    storageBucket: 'namma-kadai-d7220.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQeQXM58EgVYDeoGQk9IqulcL8jJ1jtG0',
    appId: '1:588478581327:ios:0d03245b06655684c9783a',
    messagingSenderId: '588478581327',
    projectId: 'namma-kadai-d7220',
    storageBucket: 'namma-kadai-d7220.firebasestorage.app',
    iosBundleId: 'com.example.nammaKadai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQeQXM58EgVYDeoGQk9IqulcL8jJ1jtG0',
    appId: '1:588478581327:ios:0d03245b06655684c9783a',
    messagingSenderId: '588478581327',
    projectId: 'namma-kadai-d7220',
    storageBucket: 'namma-kadai-d7220.firebasestorage.app',
    iosBundleId: 'com.example.nammaKadai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-037x_qckmCuO4UFee6L9inf3MyjzYjA',
    appId: '1:588478581327:web:f06143d40e088f2ac9783a',
    messagingSenderId: '588478581327',
    projectId: 'namma-kadai-d7220',
    authDomain: 'namma-kadai-d7220.firebaseapp.com',
    storageBucket: 'namma-kadai-d7220.firebasestorage.app',
    measurementId: 'G-VXCJZC5X9X',
  );
}
