name: Flutter Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Get dependencies
        run: flutter pub get
        working-directory: flutter_practice/namma_kadai

      - name: Build APK
        run: flutter build apk
        working-directory: flutter_practice/namma_kadai